remote_theme: mikearnaldi/just-the-docs

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
'create-lib on GitHub':
  - 'https://github.com/FunctorFactory/create-lib'